watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 10
      left: 8
      bottom: 2
      right: 8
    widgets:
      left:
        [
          "glazewm_workspaces",
          "active_window",
          "memory",
        ]
      center:
        ["clock"]
      right:
        [
          "media",
          "volume",
          "battery",
          "notifications",
          "wifi",
          "power_menu"
        ]
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "Offline!"
      hide_empty_workspaces: true
      hide_if_offline: false
      container_padding: 
        top: 0
        left: 8
        bottom: 0
        right: 8
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "\uf476"
      label_alt: "<span>\uf476</span> {count}"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_label"
        on_middle: "toggle_label"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 13
      gradient: 1
      reverse: 0
      sensitivity: 100
      foreground: "#cdd6f4"
      gradient_color_1: '#cdd6f4'
      gradient_color_2: '#cdd6f4'
      gradient_color_3: '#cdd6f4'
      bars_number: 8
      bar_spacing: 2
      bar_width: 4
      sleep_timer: 0
      hide_empty: true
      container_padding:
        top: 2
        left: 0
        bottom: 1
        right: 0
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon}"
      label_alt: "{icon} {percent}%"
      charging_options:
        icon_format: "{charging_icon}"
      status_icons:
        icon_charging: "\udb80\udc84"
        icon_critical: "\udb80\udc7a"
        icon_low: "\udb80\udc7b"
        icon_medium: "\udb80\udc7e"
        icon_high: "\udb80\udc80"
        icon_full: "\udb80\udc79"
      status_thresholds:
        critical: 10
        low: 30
        medium: 75
        high: 85
        full: 100
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_used}"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "{title}"
        label_alt: "{artist}"
        max_field_size:
          label: 18
          label_alt: 18
        show_thumbnail: false
        controls_only: false
        controls_left: true
        hide_empty: true
        thumbnail_alpha: 250
        thumbnail_padding: 8
        thumbnail_corner_radius: 0
        callbacks:
          on_left: "toggle_media_menu"
          on_middle: "do_nothing"
          on_right: "toggle_label"
        icons:
          prev_track: ""
          next_track: ""
          play: "<span>\uf001</span>"
          pause: "<span>\uf001</span>"
        media_menu:
          blur: true
          round_corners: false
          round_corners_type: "normal"
          border_color: "system"
          alignment: "right"
          direction: "down"
          offset_top: 6
          offset_left: -2
          thumbnail_corner_radius: 2
          thumbnail_size: 75
          max_title_size: 25
          max_artist_size: 32
          show_source: false
        media_menu_icons:
          play: "\uf04b"
          pause: "\uf04c"
          prev_track: "\uf04a"
          next_track: "\uf04e"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "\ue62a {win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: "\ue62a Desktop - Windows Explorer"
      label_icon: false
      label_icon_size: 14
      max_length: 30
      max_length_ellipsis: "..."
      monitor_exclusive: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: false
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'right'
        direction: 'down'
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "\uef37 {%a %b %d - %I:%M %p}"
      label_alt: "\uef37 {%A, %d %B %Y %I:%M:%S %p}"
      timezones: []
      calendar:
        blur: true
        show_holidays: true
        direction: down
        alignment: "center"
        holiday_color: "#FF6464"
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: True
        blur: True
        blur_background: true
        animation_duration: 140 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          shutdown: ["","Power off"]
          signout: ["","Exit"]
          restart: ["","Restart"]
          hibernate: ["","Hibernate"]
          cancel: ["","Cancel"]
  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        update_interval: 5000
        ethernet_icon: "\ue673"
        ethernet_label_alt: "{ip_addr}"
        animation:
          enabled: true
          duration: 100
          type: "fadeInOut"
        callbacks:
          on_left: "toggle_menu"
          on_right: "do_nothing"
          on_middle: "toggle_label"
        menu_config:
          blur: true
          round_corners: false
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
          offset_top: 5
          offset_left: -1
          wifi_icons_unsecured: [
            "\uec3c",
            "\uec3d",
            "\uec3e",
            "\uec3f",
          ]
  systray:
      type: "yasb.systray.SystrayWidget"
      options:
        class_name: "systray"
        label_collapsed: "▼"
        label_expanded: "▶"
        label_position: "left" # Can be "left" or "right"
        icon_size: 16 # Can be any integer between 8 and 64
        pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
        show_unpinned: true
        show_unpinned_button: true
        show_battery: false
        show_volume: false
        show_network: false
        container_padding:
            left: 0
            top: 0
            right: 0
            bottom: 0